### ISSUE TITLE
Ball speed and club speeds clearly incorrect

### ISSUE THREAD

**Issue by balaakay** [earl553/garminr10dataconverter#2]
Is there some kind of conversion needed to get the correct speeds from club head and ball speeds or is the script misplacing headings? All my ball speeds on all clubs are between 12 and 70 of whatever that unit is and I hit drivers in the 160-165 mph range.

Thanks for any help you can provide me!

**Comment by gregmatic** [comment]
it's in m/s.

**Comment by balaakay** [comment]
I should have considered that. Thanks!
